config/routes.rb
EventManagment::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "registrations"}
    
  root :to => 'welcome#index'

  get "welcome/manager_reg"
  post "welcome/create"
  get "welcome/create_event"
  post "welcome/create_event"
  get "welcome/show_event"
  get "welcome/manager_profile"
  get "welcome/main"
  post "welcome/main"
  get "welcome/download_pdf"
  post "welcome/download_pdf"

  get "welcome/content"
  post "welcome/content"

  

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :description, :first_name, :last_name,:user_id

  belongs_to :user
  has_many :eventinfos
  has_many :persons





end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessible :description, :title, :user_id

  belongs_to :user

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description, :name, :file
  has_many :eventinfos

    attr_accessible :file
   has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }
   # validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/
    validates_attachment_content_type :file,
      :content_type => [ 'application/pdf' ],
      :message => "only pdf files are allowed"
end

app/models/eventinfo.rb
class Eventinfo < ActiveRecord::Base
  attr_accessible :client_id, :manager_id, :person_id, :event_id,:status
 belongs_to :manager
 belongs_to :client
 belongs_to :person
 belongs_to :event
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  attr_accessible :description, :first_name, :last_name,:user_id

 belongs_to :user
 
 has_many :clients
 has_many :enveninfos, through: :clients

has_many :eventinfos


end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :first_name, :last_name,:user_id
  has_many :eventinfos
  belongs_to :user
  belongs_to :client
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  
  has_many :user_roles
  has_many :users, through: :user_roles

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :user_roles
  
   has_many :managers
    has_many :clients
    has_many :persons

    has_one :content

  has_many :roles, through: :user_roles


 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

   def self.role(user)
     @role=user.roles[0].name
     return @role
  end
   
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  attr_accessible :role_id, :user_id

  belongs_to :user
  belongs_to :role

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :authenticate_user!
  protect_from_forgery
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  def new
    super
  end

  def create
      @user=User.new(params[:user])
      if !Role.find_by_name(params[:role]).blank?
        @role = Role.find_by_name(params[:role])
        @user.user_roles.new(:role_id=>@role.id)
      else
        @user.roles.new(:name=>params[:role])
        #@user.user_roles.new()
      end
      if params[:role]=="Client"   
        @clienr=@user.clients.new(:first_name=>params[:first_name],:last_name=>params[:last_name],:description=>params[:description])   
      elsif params[:role]=="Manager"
        @manager=@user.managers.new(:first_name=>params[:first_name],:last_name=>params[:last_name],:description=>params[:description])
      elsif params[:role]=="Person"
        @person=@user.persons.new(:first_name=>params[:first_name],:last_name=>params[:last_name])
      end
      if @user.save
        sign_in_and_redirect(@user)
      else
        super    
      end
  end
end

app/controllers/welcome_controller.rb
 
class WelcomeController < ApplicationController

	before_filter :authenticate_user!, :except=>[:manager_reg,:create,:main,:create_event]
  respond_to :html, :js
  
  def index
    @person_id = Person.find_by_user_id(current_user.id)
    @eventin = Eventinfo.find_all_by_person_id(@person_id)
    @status = Eventinfo.where(:id =>params[:id]).update_all(:status => "1")
    @eventinfo = Eventinfo.find_all_by_manager_id(current_user.id)
  end

  def create_event
    @event=Event.new(params[:event])
    @event.save()
      params[:person_id].each do |id|
        @eventinfo=@event.eventinfos.new(:manager_id=>params[:event][:id],:client_id=>current_user.id,:person_id=>id,:status=>0)
        @eventinfo.save
      end    
    if @eventinfo.save
      redirect_to welcome_show_event_path	
    end
  end

  def show_event
   @eventinfo = Eventinfo.find_all_by_client_id(current_user.id)
  end  

  def manager_profile
  end

  def main
  end

  def content
    @content = current_user.content
    if @content.blank? && (!params[:title].blank? || !params[:description].blank?)
      @content = current_user.build_content(:title=>params[:title],:description=>params[:description])
      @content.save
    else
      if !params[:title].blank?
        @content.title = params[:title]
        @content.save
      end
      if !params[:description].blank?
        @content.description = params[:description]
        @content.save
      end
    end
    respond_to do |format|
      format.js
      format.html
    end
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div id="map"></div>

app/views/layouts/_header.html.erb
 <nav class="" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#page-top">
                    
                </a>
            </div>


            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <% if user_signed_in? %>
                        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
                        </li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                        </li>
                        <li><%= link_to " Title or description", welcome_content_path %> </li>
                                               
                    <% else %>
                        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %>
                        </li>
                        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                        </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseOverride</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<h2> Hello </h2> 

<%= render "/layouts/header" %>

<%= yield %>

<%= render "/layouts/footer" %>


</body>
</html>

app/views/welcome/_client.html.erb
<h2>Client</h2>

<% if params[:user].blank? %>
 <%user=User.new%>
 <%else%>
 <%user=User.new(params[:user])%>
 <%end%>


<div class="col-md-3" >
<%= form_for((user), :url => registration_path(User.new,:remote=>true)) do |f| %>
  <%#= devise_error_messages! %>
  
  <%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true, :class=>"form-control" %>

  <%= hidden_field_tag "role", 'Client' %>

  <%= label_tag :first_name %><br/>
  <%= text_field_tag :first_name,'', :class=>"form-control" %>

  <%= label_tag :last_name %><br/>
  <%= text_field_tag :last_name,'', :class=>"form-control" %>

  <%= label_tag :description %><br/>
  <%= text_area_tag :description ,'', :class=>"form-control"%>

  <%= f.label :password %><br />
  <%= f.password_field :password, :class=>"form-control" %>

  <%= f.label :password_confirmation%><br />
  <%= f.password_field :password_confirmation, :class=>"form-control"  %>

  <%= f.submit "Sign up",:class=>"btn btn-primary" %>

<% end %> 
</div>

app/views/welcome/_content.html.erb
	<h2>Title</h2>
	<div id="title-box" style="padding:10px;border:1px #ffffff solid;">
	  <% if !@content.try(:title).blank? %>
        <%= @content.title  %>
      <% else %>
     dfgfdgfdg  Please add some Title
	  <% end %>
	</div>
	<br/><br/>
	
	<h2>Description</h2>
	<div id="description-box" style="padding:10px;border:1px #ffffff solid;">
	  <% if !@content.try(:description).blank? %>
        <%= @content.description  %>
      <% else %>
      	Please add some Description
      <% end %>
	</div > 
	
<script>
	$(document).click(function (e)
	{
	    var container = $("#title");
	    var description = $("#description");
	    var container_box = $("#title-box");
	    var description_box = $("#description-box");
	    if ((!container_box.is(e.target) && container_box.has(e.target).length === 0) &&    
	    	(!description_box.is(e.target) && description_box.has(e.target).length === 0))
	    {    
             $.ajax({
	         	url: "/welcome/content?title="+container.val()+"&description="+  description.val()
	         });
		}   
    });

    $(document).ready(function(){
	    $("#title-box").click(function(){
			 if ($("#title-box #add-title").length == 0){
				$("#title-box").html('<div id="add-title"><input id="title" name="title" type="text"></div>')
			 }
		});

		$("#description-box").click(function(){
			 if ($("#description-box #add-description").length == 0){
				$("#description-box").html('<div id="add-description"><input id="description" name="description" type="text"></div>')
			 }
		});

    });


</script>

app/views/welcome/_create_event.html.erb
<h2>Create an event</h3>
 <div class="col-md-3" > 
<%= form_for((Event.new), :url => welcome_create_event_path(Event.new), :multipart => true ) do |f| %>
  Select manager for event <%= f.collection_select :id, Manager.order(:first_name),:id,:first_name, {}, {:class=> "form-control"} %><br/>
  
    <%= check_box_tag "check_all",'fdssdf' %>Selet all checkbox
    <% Person.all.each do |person| %>
      <% if !person.id.blank? %>
        <%= check_box_tag "person_id[]", person.id,'',:class=>'checkbox1' %>
        <%= person.first_name %>
      <% end %>  
    <% end %>
  <br/>

     Event<%= f.label :name %><br/>
     <%= f.text_field :name,:class=>"form-control"%>

     <%= f.label :description %></br>
     <%= f.text_area :description ,:class=>"form-control"%>

     <%= f.label :date %><br/>
     <%= f.date_select :date ,{:prompt => { :day => 'Select day', :month => 'Select month', :year => 'Select year' }}, {:class=>"form-control"}  %><br/>
    
     <%= f.label :file %>
     <%= f.file_field :file ,:multipart => true,:class=>"form-control"  %>
      

  <%= f.submit "Submit",:class=>"btn btn-primary" %><br/>
<% end %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#check_all').click(function(event) {  //on click
        if(this.checked) { // check select status
            $('.checkbox1').each(function() { //loop through each checkbox
                this.checked = true;  //select all checkboxes with class "checkbox1"              
            });
        }else{
            $('.checkbox1').each(function() { //loop through each checkbox
                this.checked = false; //deselect all checkboxes with class "checkbox1"                      
            });        
        }
    });
   
  });
</script>

app/views/welcome/_manager_profile.html.erb
<h1> Manager</h1>
<table  class="table table-bordered table-condensed" >
  <th>Event Name</th><th>Event Description </th><th>Event Date</th><th>Status</th>
  <% @eventinfo.each do |eventinfo| %>
    <tr >
      <td> <%= eventinfo.event.name %>  </td>
      <td>  <%= eventinfo.event.description %></td>
      <td> <%=eventinfo.event.date.strftime("%Y-%B-%e") %></td>
      <% if !eventinfo.status %>
         <td><%= link_to 'Approve', root_path(:id=>eventinfo.id), data: {remote: true} %></td>
      <% else %>
       <td> you are approve this event</td>
      <% end %>  
    </tr>
  <% end %>
</table>

app/views/welcome/_manager_reg.html.erb
<h2>Manager</h2>
 
 <% if params[:user].blank? %>
 <%user=User.new%>
 <%else%>
 <%user=User.new(params[:user])%>
 <%end%>
<div class="col-md-3" >
<%= form_for((user), :url => registration_path(User.new,:remote=>true)) do |f| %>
  <%#= devise_error_messages! %>

  <%= f.label :email %><br/>
  <%= f.email_field :email, :class=>"form-control"%>

  <%= hidden_field_tag "role",'Manager' %>

  <%= label_tag :first_name %><br/>
  <%= text_field_tag :first_name,'', :class=>"form-control"%><br/>

 <%= label_tag :last_name %><br/>
  <%= text_field_tag :last_name,'', :class=>"form-control"%><br/>

  <%= label_tag :description %><br/>
  <%= text_area_tag :description,'', :class=>"form-control"%><br/>

  <%= f.label :password %><br />
  <%= f.password_field :password, :class=>"form-control"%><br/>

  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, :class=>"form-control"%><br/>

 <%= f.submit "Sign up",:class=>"btn btn-primary" %>

<% end %> 
</div>

app/views/welcome/_person.html.erb
<h2>Person</h2>

 <% if params[:user].blank? %>
 <%user=User.new%>
 <%else%>
 <%user=User.new(params[:user])%>
 <%end%>

 
<div class="col-md-3" >
<%= form_for((user),:url => registration_path(User.new,:remote=>true)) do |f| %>
  <%#= devise_error_messages! %>
  
 <%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true, :class=>"form-control" %>
  <%= hidden_field_tag "role", 'Person' %>

<%= label_tag :first_name %><br/>
  <%= text_field_tag :first_name,'', :class=>"form-control" %>

<%= label_tag :last_name %><br/>
  <%= text_field_tag :last_name ,'', :class=>"form-control"%>
<%= f.label :password %><br />
  <%= f.password_field :password , :class=>"form-control" %>

<%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, :class=>"form-control" %>
<%= f.submit "Sign up"%>

<% end %> 
</div>

app/views/welcome/_person_profile.html.erb
<% link_to "title",welcome_content_path  %>
<h1>Person</h1>
 <%#debugger%>
<table  class="table table-bordered table-condensed" >
     <tr><th>Client_name</th><th>Event Name</th><th>Event Description </th><th>Event Date</th></tr>
     <% @eventin.each do |eventin| %>
	   <% if !eventin.event.blank? %>
	       <tr>
	       	<%if !Client.find_by_user_id(eventin.client_id).blank? %>
	        	<td><%=Client.find_by_user_id(eventin.client_id).first_name %></td>
	        <%end%>
			    <td><%= eventin.event.name %></td>
			    <td><%= eventin.event.description %></td>
			    <td><%= eventin.event.date.strftime("%Y-%B-%e") %></td>
		   </tr>    
	   <% end %>  
	 <% end %>
</table>  

app/views/welcome/content.html.erb
<div style="background:#ffffff;padding:40px;min-height:400px;color:#000000;">
	<div id="content-main">
		<%= render 'content' %>
	</div>
	
	<div id="title-field" class="col-md-3"  style="display:none;" >
		<%=text_field_tag :title,'', :class=>"form-control"%>
	</div>
	
	<div id="description-field" class="col-md-3" style="display:none;"   >	
		<%=text_field_tag :description,'', :class=>"form-control"  %>
	</div>
	
</div>
<style type="text/css">
 #description-box:hover
 {
 	border:1px #000000 solid !important;
 }
 #title-box:hover
 {
 	border:1px #000000 solid !important;
 }
</style>
<script type="text/javascript">
	$(document).click(function (e)
	{
	    var container = $("#title");
	    var description = $("#description");
	    var container_box = $("#title-box");
	    var description_box = $("#description-box");
	    if ((!container_box.is(e.target) && container_box.has(e.target).length === 0) &&    
	    	(!description_box.is(e.target) && description_box.has(e.target).length === 0))
	    {
		    
             $.ajax({
	         	url: "/welcome/content?title="+container.val()+"&description="+  description.val()
	         });
		
		}

    });

    $(document).ready(function(){
	    $("#title-box").click(function(){
			 if ($("#title-box #add-title").length == 0){
				$("#title-box").html('<div id="add-title"><input id="title" name="title" type="text"></div>')
			 }
		});

		$("#description-box").click(function(){
			 if ($("#description-box #add-description").length == 0){
				$("#description-box").html('<div id="add-description"><input id="description" name="description" type="text"></div>')
			 }
		});

    });



</script>

app/views/welcome/content.js.erb
$("#content-main").html("<%= escape_javascript(render(:partial => "content"))%>");

app/views/welcome/index.html.erb
<%if User.role(current_user)=="Client" %>
  <%=render "/welcome/create_event"%>
<% elsif User.role(current_user)=="Manager" %>
  <div id="approve">
	<%=render "/welcome/manager_profile" %>
  </div>
<% elsif User.role(current_user)=="Person" %>  
    <%=render "/welcome/person_profile" %>
<% end %>

app/views/welcome/index.js.erb
$("#approve").html("<%= escape_javascript(render(:partial => "manager_profile"))%>");

app/views/welcome/main.html.erb
 <section class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Grayscale</h1>
                        <p class="intro-text">A free, premium quality, responsive one page Bootstrap theme created by Start Bootstrap.</p>
                        <div class="page-scroll">
                            <a href="#about" class="btn btn-circle">
                                <i class="fa fa-angle-double-down animated"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About Grayscale</h2>
                <p>Grayscale is a premium quality, free Bootstrap 3 theme created by Start Bootstrap. It can be yours right now, all you need to do is download the template on the preview page. You can use this template for any purpose, personal or commercial.</p>
                <p>This striking, black and white theme features stock photographs by <a href="http://gratisography.com/">Gratisography</a> along with a custom Google Map skin courtesy of <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p>
                <p>With this template, just the slightest splash of color can make a huge impact on the overall presentation and design.</p>
            </div>
        </div>
    </section>

    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Download Grayscale</h2>
                    <p>You can download Grayscale for free on the download page at Start Bootstrap. You can also get the source code directly from GitHub if you prefer. Additionally, Grayscale is the first Start Bootstrap theme to come with a LESS file for easy color customization!</p>
                    <a href="http://startbootstrap.com/grayscale" class="btn btn-default btn-lg">Visit Download Page</a>
                </div>
            </div>
        </div>
    </section>

    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact Start Bootstrap</h2>
                <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>
                <p>feedback@startbootstrap.com</p>
                <ul class="list-inline banner-social-buttons">
                    <li><a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li><a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li><a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    

    <!-- Core JavaScript Files -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Google Maps API Key - You will need to use your own API key to use the map feature -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/grayscale.js"></script>

app/views/welcome/manager_reg.js.erb
<% if params[:role] == "Manager" %>
     
    $("#redio").html("<%= escape_javascript(render(:partial => "manager_reg"))%>");
  <% elsif params[:role] == "Client" %>
    $("#redio").html("<%= escape_javascript(render(:partial => "client"))%>");
  <% elsif params[:role] == "Person" %>
    $("#redio").html("<%= escape_javascript(render(:partial => "person"))%>");
<% end %>

app/views/welcome/show_event.html.erb
  
<h2>Your events</h2>
  <table class="table table-bordered table-condensed">
    <tr>
      <th>EventName</th>
      <th>Description</th>
      <th>Date </th> 
      <th>File Download</th> 
      <th>Your pdf</th>
    </tr>
    <% @eventinfo.each do |eventinfo| %>
    
      <% if !eventinfo.event.blank? %>
        <tr>
      		<td> <%= eventinfo.event.name %></td>
          <td>  <%= eventinfo.event.description %></td>
          <td> <%=eventinfo.event.date.strftime("%Y-%B-%e") %></td>
          <td><%= link_to 'Downlaod my PDF', eventinfo.event.file.url %></td>
          <td> <iframe src="https://docs.google.com/viewer?url=<%=eventinfo.event.file.url%>&embedded=true" style="height: 300px;" frameborder="0">
              </iframe> 
             <!--  <a href="http://localhost:3000<%= eventinfo.event.file.url  %>&embedded=true">Your Pdf Viewer</a> -->
          </td>
        </tr>
      <% end %>  
    <% end %>
  </table>

  